//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Game), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetGame", GetGame);
		L.RegFunction("ChangeRgn", ChangeRgn);
		L.RegFunction("LoadScene", LoadScene);
		L.RegFunction("AddScene", AddScene);
		L.RegFunction("DelScene", DelScene);
		L.RegFunction("GetTime", GetTime);
		L.RegFunction("GetDeltaTime", GetDeltaTime);
		L.RegFunction("GetRay", GetRay);
		L.RegFunction("OnCreateInvoke", OnCreateInvoke);
		L.RegFunction("GetNewGuid", GetNewGuid);
		L.RegFunction("GetEventSystemOverGameObject", GetEventSystemOverGameObject);
		L.RegFunction("GetCurActiveScene", GetCurActiveScene);
		L.RegFunction("World2UI", World2UI);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("strChangeRgn", get_strChangeRgn, set_strChangeRgn);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetGame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Game o = Game.GetGame();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ChangeRgn(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Game obj = (Game)ToLua.CheckObject<Game>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ChangeRgn(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadScene(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Game obj = (Game)ToLua.CheckObject<Game>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.LoadScene(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddScene(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Game obj = (Game)ToLua.CheckObject<Game>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.AddScene(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DelScene(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Game obj = (Game)ToLua.CheckObject<Game>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.DelScene(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTime(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Game obj = (Game)ToLua.CheckObject<Game>(L, 1);
			float o = obj.GetTime();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDeltaTime(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Game obj = (Game)ToLua.CheckObject<Game>(L, 1);
			float o = obj.GetDeltaTime();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetRay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			Game obj = (Game)ToLua.CheckObject<Game>(L, 1);
			UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 2);
			UnityEngine.Vector2 arg1 = ToLua.ToVector2(L, 3);
			float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
			int arg3 = (int)LuaDLL.luaL_checknumber(L, 5);
			bool o = obj.GetRay(arg0, arg1, arg2, arg3);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnCreateInvoke(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Game obj = (Game)ToLua.CheckObject<Game>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			obj.OnCreateInvoke(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNewGuid(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Game obj = (Game)ToLua.CheckObject<Game>(L, 1);
			string o = obj.GetNewGuid();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetEventSystemOverGameObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Game obj = (Game)ToLua.CheckObject<Game>(L, 1);
			bool o = obj.GetEventSystemOverGameObject();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCurActiveScene(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Game obj = (Game)ToLua.CheckObject<Game>(L, 1);
			string o = obj.GetCurActiveScene();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int World2UI(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Game obj = (Game)ToLua.CheckObject<Game>(L, 1);
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			UnityEngine.Vector3 o = obj.World2UI(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_strChangeRgn(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Game obj = (Game)o;
			string ret = obj.strChangeRgn;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index strChangeRgn on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_strChangeRgn(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Game obj = (Game)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.strChangeRgn = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index strChangeRgn on a nil value");
		}
	}
}

